public class XeroOrganisation {
	
	public Organisations[] Organisations;

	public class Organisations {
		public String APIKey;	//PV1PS57LYQ7VDJYTGCUI99A6YJI1WZ
		public String Name;	//Demo Company NZ
		public String LegalName;	//Demo Company NZ
		public String PaysTax;	//true
		public String Version;	//NZ
		public String OrganisationType;	//COMPANY
		public String BaseCurrency;	//NZD
		public String CountryCode;	//NZ
		public String IsDemoCompany;	//true
		public String OrganisationStatus;	//ACTIVE
		public String TaxNumber;	//101-2-303
		public String OrganisationID;	//c3d5e782-2153-4cda-bdb4-cec791ceb90d
	}
}