public without sharing class XeroRevenueCodes {
	public String ProviderName ;
	public Accounts[] Accounts;

	public class Accounts {
		public String AccountId;	//a4616501-4248-4ec8-ab6c-04a69fa0c6c0
		public String Code;	//200
		public String Name;	//Sales
		public String Status;	//ARCHIVED
		public String Type;	//REVENUE
		public String Description;	//Income from any normal business activity
	}
}