public with sharing class XeroContact_Create {
	public String ContactID;
	public String ContactStatus;
	public String Name;
	public String FirstName;
	public String LastName;
	public String EmailAddress;
	public String BankAccountDetails;
	public String SkypeUserName;
    //public XeroAddress[] Addresses;
	//public XeroPhone[] Phones;
	public String UpdatedDateUTC;
	//public ContactGroups[] ContactGroups;
	public Boolean IsSupplier;
	public Boolean IsCustomer;
	public String DefaultCurrency;
	//public Balances Balances;
	//public ContactPersons[] ContactPersons;
	public Boolean HasAttachments;
	//public Attachments[] Attachments;
	public Boolean HasValidationErrors;
}